spring:
  datasource:
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      connection-test-query: SELECT 1
  data:
    redis:
      host: redis
      port: 6379